version: '3'
services:
  mysql:
    # docker exec で入れるようになったとしても
    # しばらく時間を置かないと正常にmysqlにはログインできずその上コンテナが落ちることがある　なんで・・・
    # 1分くらい待ってから入ると普通にログインできた
    build: ./mysql
    hostname: mysql
    container_name: mysql
    tty: true

    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'

  engine:
    hostname: engine
    build: ./engine
    container_name: engine
    environment:
      ENGINE_USER_PASSWORD: ${ENGINE_USER_PASSWORD}
    restart: always


  api:
    build: ./api
    container_name: api
    hostname: api
    restart: always
    environment:
      API_USER_PASSWORD: ${API_USER_PASSWORD}
      PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - "./api/src:/src"

  manager:
    build: ./manager
    container_name: manager
    hostname: manager
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ENGINE_USER_PASSWORD: ${ENGINE_USER_PASSWORD}
      API_USER_PASSWORD: ${API_USER_PASSWORD}
    depends_on: [mysql]

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
